import * as crypto from 'crypto';

/**
 * AuthIDIssuer generates secure authentication IDs for cosigner sessions
 * using HMAC-SHA3-256 with an atomic counter and timestamp
 */
export class AuthIDIssuer {
  private authIdIter: number;
  private hmacKey: Buffer;

  constructor(hmacKey: Buffer) {
    this.authIdIter = 0;
    this.hmacKey = hmacKey;
  }

  /**
   * Creates a new authentication ID
   *
   * The auth ID is generated by:
   * 1. Incrementing an atomic counter
   * 2. Combining counter + timestamp (16 bytes total)
   * 3. Computing HMAC-SHA3-256 over the combined value
   * 4. Returning the hex-encoded HMAC
   *
   * @param timeNow - Current timestamp in seconds (Unix time)
   * @returns Hex-encoded authentication ID
   */
  createAuthID(timeNow: number): string {
    // Increment the counter atomically
    this.authIdIter += 1;
    const authIdInt = this.authIdIter;
    // Create buffer with counter and timestamp (16 bytes total: 8 + 8)
    const iterAndTime = Buffer.alloc(16);
    // Write as little-endian uint64 values
    iterAndTime.writeBigUInt64LE(BigInt(authIdInt), 0);
    iterAndTime.writeBigUInt64LE(BigInt(timeNow), 8);
    // Compute HMAC-SHA3-256
    const hmac = crypto.createHmac('sha3-256', this.hmacKey);
    hmac.update(iterAndTime);
    const digest = hmac.digest();
    // Return hex-encoded result
    return digest.toString('hex');
  }
}

/**
 * Creates a new AuthIDIssuer with the given HMAC key
 *
 * @param hmacKey - Secret key for HMAC generation (recommend 32+ bytes)
 * @returns A new AuthIDIssuer instance
 */
export function newAuthIDIssuer(hmacKey: Buffer): AuthIDIssuer {
  return new AuthIDIssuer(hmacKey);
}
